Ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from .views import (ItemDetailView,
                    CheckoutView,
                    IndexView,
                    add_to_cart,
                    remove_from_cart,
                    OrderSummaryView,
                    remove_single_item_from_cart,
                    add_single_item_to_cart,
                    PaymentView,
                    AddCouponView,
                    RequestRefundView)

app_name = 'core'
urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('product/<slug>/', ItemDetailView.as_view(), name="product"),
    path('checkout/', CheckoutView.as_view(), name="checkout-page"),
    path('order-summary/', OrderSummaryView.as_view(), name="order-summary"),
    path('add-to-cart/<slug>', add_to_cart, name="add-to-cart"),
    path('remove-from-cart/<slug>', remove_from_cart, name="remove-from-cart"),
    path('remove-item-from-cart/<slug>', remove_single_item_from_cart, name="remove-single-item-from-cart"),
    path('add-single-item-to-cart/<slug>', add_single_item_to_cart, name="add-single-item-to-cart"),
    path('payment/<payment_option>/', PaymentView.as_view(), name="payment"),
    path('add-coupon/', AddCouponView.as_view(), name="add-coupon"),
    path('request-refund/', RequestRefundView.as_view(), name="request-refund"),
]

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse

CATEGORY_CHOICE = (
    ('S', 'Shirt'),
    ('SP', 'Sports'),
    ('W', 'Winter'),
    ('P', 'Party Wear'),
    ('F', 'Formals'),
    ('C', 'Casuals'),
    ('B', 'Bikini'),
)

Label_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

""" All the Items available for shopping """
class Item(models.Model):
    title = models.CharField(max_length=300)
    image = models.ImageField(default="default.jpg")
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICE, max_length=2)
    label = models.CharField(choices=Label_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField(default="This is a Fake Description")
    bestseller = models.BooleanField(default=False)
    isNewItem = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })
    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

""" Items which are being ordered"""
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    def get_total_price(self):
        if not self.item.discount_price:
            return self.quantity * self.item.price
        else:
            return self.quantity * self.item.discount_price
    def get_total_savings(self):
        return self.quantity * (self.item.price - self.item.discount_price)


"""All ordered Items together like a shopping cart"""
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=30, default=0)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)


    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username
    def get_final_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    email = models.EmailField()
    address = models.TextField()
    address2 = models.TextField(blank=True, null=True)
    state = models.CharField(max_length=200, blank=True, null=True)
    district = models.CharField(max_length=200, blank=True, null=True)
    zipcode = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()
    def __str__(self):
        return self.code


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.stripe_charge_id


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    def __str__(self):
        return f"{self.pk}"

templates/base.html
<!DOCTYPE html>

{% include "head.html" %}

<body>
<div class="mt-5 pt-4">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </ul>
    {% endif %}
</div>
{% include "navbar.html" %}
{% block content %}

{% endblock content %}
{% include "footer.html" %}
{% include "scripts.html" %}
{% block extra_body %}
{% endblock %}

</body>

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}

    <body class="grey lighten-3">

    <!--Main layout-->
    <main>
        <div class="container wow fadeIn">

            <!-- Heading -->
            <h2 class="my-5 h2 text-center">Checkout form</h2>

            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-md-8 mb-4">

                    <!--Card-->
                    <div class="card">

                        <!--Card content-->
                        <form method="post" class="card-body">
                            {% csrf_token %}
                            <!--email-->
                            <div class="md-form mb-5">
<!--                                <input type="text" id="email" class="form-control" placeholder="youremail@example.com">
    -->                         {{form.email}}
                                <label for="email" class="">Email Address</label>
                            </div>

                            <!--address-->
                            <div class="md-form mb-5">
                                <!---<input type="text" id="address" class="form-control" placeholder="1234 Main St"> --->
                                {{form.address}}
                                <label for="address" class="">Address</label>
                            </div>

                            <!--address-2-->
                            <div class="md-form mb-5">
         <!---                       <input type="text" id="address-2" class="form-control" placeholder="Apartment or suite">
              -->               {{ form.address2 }}
                                <label for="address-2" class="">Address 2 (optional)</label>
                            </div>

                            <!--Grid row-->
                            <div class="row">


                                <!--Grid column-->
                                <div class="col-lg-4 col-md-6 mb-4">

                                    <label for="zip">State</label>
            <!--                        <input type="text" class="form-control" id="zip" placeholder="" required>
                -->                 {{ form.state }}
                                    <div class="invalid-feedback">
                                        Enter your State
                                    </div>

                                </div>
                                <!--Grid column-->

                                <!--Grid column-->
                                <div class="col-lg-4 col-md-6 mb-4">

                                    <label for="zip">District</label>
              <!--                      <input type="text" class="form-control" id="zip" placeholder="" required>
                  -->               {{ form.district }}
                                    <div class="invalid-feedback">
                                        Enter the district
                                    </div>

                                </div>
                                <!--Grid column-->


                                <!--Grid column-->
                                <div class="col-lg-4 col-md-6 mb-4">

                                    <label for="zip">Zip</label>
            <!--                        <input type="text" class="form-control" id="zip" placeholder="" required>
                -->                 {{ form.zipcode }}
                                    <div class="invalid-feedback">
                                        Zip code required.
                                    </div>

                                </div>
                                <!--Grid column-->

                            </div>
                            <!--Grid row-->

                            <hr>

                            <div class="custom-control custom-checkbox">
                                <input {% if form.same_billing_address.value %} checked {% endif %} type="checkbox" class="custom-control-input" name="same_billing_address" id="same-address">
                                <label class="custom-control-label" for="same-address">Shipping address is the same as
                                    my billing address</label>
                            </div>
                            <div class="custom-control custom-checkbox">
                                <input {% if form.save_info.value %} checked {% endif %} type="checkbox" class="custom-control-input" name="save_info" id="save-info">
                                <label class="custom-control-label" for="save-info">Save this information for next
                                    time</label>
                            </div>

                            <hr>

                            <div class="d-block my-3">
                                {% for value, name in form.fields.payment_option.choices %}
                                <div class="custom-control custom-radio">
                                    <input id="{{name}}" name="payment_option" type="radio" value="{{ value }}" class="custom-control-input"
                                            required>
                                    <label class="custom-control-label" for="{{name}}">{{ name }}</label>
                                </div>
                                {% endfor %}
{#                                <div class="custom-control custom-radio">#}
{#                                    <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input"#}
{#                                           required>#}
{#                                    <label class="custom-control-label" for="paypal">Paypal</label>#}
{#                                </div>#}
                            </div>
                            <hr class="mb-4">
                            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

                        </form>

                    </div>
                    <!--/.Card-->

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-4 mb-4">

                    {% include 'order_snippet.html' %}

                    <!-- Promo code -->
                    <form class="card p-2" method="post" action="{% url 'core:add-coupon' %}">
                        {% csrf_token %}
                        <div class="input-group">
{#                            <input type="text" class="form-control" placeholder="Promo code"#}
{#                                   aria-label="Recipient's username" aria-describedby="basic-addon2">#}
                            {{ couponform.code }}
                            <div class="input-group-append">
                                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                            </div>
                        </div>
                    </form>
                    <!-- Promo code -->

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

        </div>
    </main>
    <!--Main layout-->

{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <!--Main layout-->
    <main>
        <div class="container">

            <!--Navbar-->
            <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

                <!-- Navbar brand -->
                <span class="navbar-brand">Categories:</span>

                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">

                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/">All
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Shirts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Sport wears</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Outwears</a>
                        </li>

                    </ul>
                    <!-- Links -->

                    <form class="form-inline">
                        <div class="md-form my-0">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                        </div>
                    </form>
                </div>
                <!-- Collapsible content -->

            </nav>
            <!--/.Navbar-->

            <!--Section: Products v.3-->
            <section class="text-center mb-4">

                <!--Grid row-->
                <div class="row wow fadeIn">
                    {% for item in object_list %}
                        <div class="col-lg-3 col-md-6 mb-4">
                            <div class="card">
                                <div class="view overlay">
                                    <img src="{{ item.image.url }}" class="card-img-top" width="330px"
                                         alt="">

                                    <a href="{{ item.get_absolute_url }}">
                                        <div class="mask rgba-white-slight"></div>
                                    </a>
                                </div>
                                <div class="card-body text-center">
                                    <a href="{{ item.get_absolute_url }}" class="grey-text">
                                        <h5>{{ item.get_category_display }}</h5></a>
                                <div class="m-md-1">{% if item.bestseller %}
                                            <span class="badge badge-pill secondary-color">
                                            BESTSELLER
                                            </span>
                                        {% endif %}
                                        {% if item.isNewItem %}
                                            <span class="badge badge-pill primary-color">
                                            NEW
                                            </span>
                                        {% endif %}</div>
                                    <h5><strong><a href="{{ item.get_absolute_url }}"
                                                   class="dark-grey-text">{{ item.title }}
                                        </a>
                                    </strong></h5>

                                    <h4 class="font-weight-bold blue-text"><strong>$
                                        {% if item.discount_price %}
                                            {{ item.discount_price }}
                                        {% else %}
                                            {{ item.price }}
                                        {% endif %}
                                    </strong></h4>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!--Grid row-->

            </section>
            <!--Section: Products v.3-->

            <!--Pagination-->
            {% if is_paginated %}
                <nav class="d-flex justify-content-center wow fadeIn">
                    <ul class="pagination pg-blue">

                        <!--Arrow left-->
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                        {% endif %}
                        <li class="page-item active">
                            <a class="page-link" href="">{{ page_obj.number }}
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
            <!--Pagination-->

        </div>
    </main>
    <!--Main layout-->


{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">E1-Commerce Django</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout/">Checkout</a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
            <li class="nav-item mr-2">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{request.user | cart_item_count}} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
            </li>
            <li class="nav-item mr-2">
            <a class="nav-link border border-light rounded waves-effect" href="{% url 'account_logout' %}">
              <i class="fas fa-user"></i>
              <span class="clearfix d-none d-sm-inline-block "> LogOut </span>
            </a>
            </li>
          {% else %}
            <li class="nav-item mr-2">
            <a class="nav-link border border-light rounded waves-effect" href="{% url 'account_login' %}">
              <i class="fas fa-user"></i>
              <span class="clearfix d-none d-sm-inline-block"> LogIN </span>
            </a>
            </li>
            <li class="nav-item">
            <a class="nav-link border border-light rounded waves-effect" href="{% url 'account_signup' %}">
              <i class="fas fa-user"></i>
              <span class="clearfix d-none d-sm-inline-block"> SignUp </span>
            </a>
            </li>
          <li class="nav-item ml-2">
            <a href="https://github.com/piyushsingariya/Ecommerce-django" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              <i class="fab fa-github mr-2"></i>E1-Commerce GitHub
            </a>
          </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

templates/order_summary.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <!--Main layout-->
    <main>
        <div class="container">
            <div class="table-responsive">
                <h2>Order Summary</h2>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Item Title</th>
                        <th scope="col">Price</th>
                        <th scope="col">Discounted Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order_item in object.items.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_item.item.title }}</td>
                            <td>${{ order_item.item.price }}</td>
                            <td>
                                {% if order_item.item.discount_price %}
                                    ${{ order_item.item.discount_price }}
                                {% else %}
                                    N/A
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                                {{ order_item.quantity }}
                                <a href="{% url 'core:add-single-item-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                            </td>
                            <td>${{ order_item.get_total_price }}
                                {% if order_item.item.discount_price %}
                                    <span class="badge badge-success ml-1">Savings ${{ order_item.get_total_savings }}</span>
                                {% endif %}

                        <a href="{% url 'core:remove-from-cart' order_item.item.slug %}"><i class="fas fa-trash float-right"></i></a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td class="font-weight-bold" colspan="5">Your Cart is empty</td>
                            <td class="font-weight-bold" colspan="5">
                                <a class="btn btn-primary ml-2" href='/'> Continue Shopping</a>
                            </td>
                        </tr>
                    {% endfor %}
                    {% if object.coupon %}
                        <tr>
                            <td class="font-weight-bold" colspan="5">Coupon</td>
                            <td  colspan="5">
                                -${{ object.coupon.amount }}
                            </td>
                        </tr>
                    {% endif %}
                    {% if object.get_final_price %}
                        <tr>
                            <td class="font-weight-bold" colspan="5">Order Total</td>
                            <td class="font-weight-bold">${{ object.get_final_price }}</td>
                        </tr>
                        <tr>
                            <td class="font-weight-bold" colspan="5">
                                <a class="btn btn-info" href='/checkout/'> Proceed to checkout</a>
                                <a class="btn btn-primary ml-2" href='/'> Continue Shopping</a>
                            </td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>

        </div>
    </main>
    <!--Main layout-->


{% endblock content %}

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <!--Main layout-->
  <main>
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ item.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            {% if item.isNewItem %}
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
            {% endif %}
            {% if item.bestseller %}
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            {% endif %}
            </div>

            <p class="lead">
              <span class="mr-1">
              {% if item.discount_price %}
                <del>${{item.price}}</del>
              {% endif %}
              </span>
              <span>$
                  {% if item.discount_price %}
                    {{ item.discount_price }}
                    {% else %}
                    {{ item.price }}
                    {% endif %}</span>
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{item.description}}</p>

            <!--<form class="d-flex justify-content-left">
              Default input
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> -->
              <a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
              <a href="{{ item.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">Remove from Cart
              </a>
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

{% endblock content %}